### ISSUE TITLE
Seeking suggestions for database development (HMDB version 5)

### ISSUE THREAD

**Issue by AnupamGautam** [rformassspectrometry/CompoundDb#107]
Dear Developers,

I am trying to develop the HMDB database based on the version 5 release, to annotate m/z generated by XCMS analysis on samples(LC-MS). I am following the protocol described on the package Github pages.

For the function **msms_spectra_hmdb(xml_path)** do all the XML files need to be present in one directory or function can also look for the XML file in a subdirectory within the specified directory? as I have downloaded the suggested hmdb_all_spectra.zip from HMDB but on unzipping, I found there are subdirectory containing more XML files (also sub-subdirectory and so on.., highlighted in the attached image).
 
Also is there any database specific to mouse metabolome (MMMDB is not accessible)? or we can use HMDB in general for m/z generated on processing mouse samples(LC-MS).

![Screen Shot 2022-06-21 at 17 52 30](https://user-images.githubusercontent.com/25628874/174846778-b582283e-c1a0-46ba-9962-685795ea60d5.png)

Thanks,
Anupam

**Comment by jorainer** [comment]
Dear Anupam,

yes, the xml files should be all in one folder. Also, maybe it might be better to *just* download the "MS/MS Spectra Files (XML) - Experimental" - you will not need the NMR or GC-MS spectra.

Regarding mouse - I don't know where (or if) you could download the mouse metabolome data - and I don't think they will follow the same format than HMDB, thus you might not be able to import that data. But AFAIK many metabolites are the same across species, so using HMDB might be maybe a good starting point?

**Comment by AnupamGautam** [comment]
Dear Johannes,

Thank you for the suggestions, I figured out that the function doesn't recursively check in the subdirectory, but didn't knew that we only need the experimental ms_ms file (thank you for the information).

For the mouse, I will proceed with HMDB for now.

Regards,
Anupam
