### ISSUE TITLE
Pass skipErrors to read.SDFset through compound_tbl_sdf?

### ISSUE THREAD

**Issue by nlichti** [rformassspectrometry/CompoundDb#110]
Hi.  `ChemmineR::read.SDFset` is throwing an error (below) when using `compound_tbl_sdf` with the current ChEBI download (accessed 11/6/2022).  As a workaround, I'm calling `debugonce(ChemmineR::read.SDFset)` and manually setting `skipErrors = TRUE`, but it would be helpful to be able to pass it through `compound_tbl_sdf` in this situation.

`Error in value[[3L]](cond) : 
  failed to parse item 10071: Error in exindex[x, 1]: subscript out of bounds`

**Comment by nlichti** [comment]
Also, I think line 94 in `createCompoundDbPackage.R` should probably read,
`res <- .simple_extract_compounds_sdf(datablock2ma(datablock(sdf)))`
not,
`res <- .simple_extract_compounds_sdf(datablock2ma(datablock(read.SDFset(file))))`

**Comment by jorainer** [comment]
Thanks for pointing this out! I'll have a look into it!

**Comment by jorainer** [comment]
@nlichti , can you please install the version with the tentative fix to see if you still get the error? I added the parameter `nonStop` to the function (this parameter was already used for the MoNA import function skipping errors).

You can install it with `BiocManager::install("RforMassSpectrometry/CompoundDb", ref = "RELEASE_3_16")`. If that fixes your error I will push to Bioconductor.

**Comment by nlichti** [comment]
@jorainer, Looks like that worked. Thanks!
