### ISSUE TITLE
The *object-oriented annotation database* concept

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/CompoundDb#41]
The following idea might be quite useful for e.g. lab-specific annotations. The idea is to have main, static, annotations e.g. from HMDB or Massbank and allow users to add lab specific annotations (such as retention times for specific compounds) too. In the sketch below, the `CompDb` object would represent a static annotation resource (getting annotations from e.g. a database). An additional object `XCompDb` could now **extend** the `CompDb` object and inherit thus all of its methods (and along with that the data) but it could also add additional annotations, such as retention times. These could even just be provided by a `data.frame` or an `xls` sheet. The point is that such `XCompDb` objects would allow to provide *dynamic* annotations e.g. for a specific LC-MS setup in a lab. Another possibility would be to add MS2 spectra measured in the lab to an existing `CompDb` that provides also MS2 spectra. The object extending `CompDb` would simply contain a `Spectra` with the MS2 spectra and whenever `spectra` is called on it (or a MS2 search is performed) it joins its MS2 spectra with those from the main database.

I think this might be quite helpful to cover the rather heterogenous and lab-specific annotations that are around. We could build on some public resources and build around them. @stanstrup @michaelwitting @sneumann what do you think?

The simple sketch for this setup:

![CompoundDb](https://user-images.githubusercontent.com/5506112/66205071-b8c21000-e6ac-11e9-88a4-d7952eebde25.png)

**Comment by stanstrup** [comment]
Sounds very reasonable to me. so `XCompDb` Could basically be any info you wanted to add?

**Comment by jorainer** [comment]
That's the plan. Having a *base* `CompDb` class and then e.g. a `RtimeCompDb` class that provides in addition *retention times* for some of the compounds available in `CompDb`. In such a `RtimeCompDb` users could put their own data and perform an annotation based on m/z **and** rtime. The benefit I think is that we don't have to think of all possible scenarios for the class/database layout. The base layout should simply reflect what is publicly available, and we build on that and extend it (without altering the base layout). Thus it's somehow like *object oriented programming*.

**Comment by stanstrup** [comment]
But `RtimeCompDb` implies a specific object for RT right? What if you wanted to add random annotation? From whatever prediction tool for example?

**Comment by jorainer** [comment]
The rtime was just an example - you could have additional objects/classes, I would not want to limit to e.g. the `RtimeCompDb` as only class. The idea is to have several classes which could be sort of plugged-in to the annotation process.

**Comment by stanstrup** [comment]
Got it. So content specific class (not an attach whatever data.frame class).
Yes this would be very nice.

Perhaps there could be a formal way to link feature tables entries and `CompDb` entries?

**Comment by jorainer** [comment]
This is now implemented with the `CompDb` and the `IonDb`.
