### ISSUE TITLE
Add new spectra to an `CompDb` database

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/CompoundDb#61]
This is related to issue https://github.com/rformassspectrometry/Spectra/issues/135 . Would be nice to have an *expandable* database, e.g. pre-fill with MS2 spectra from a public repository and then (sequentially) add own spectra and annotations to it.

Maybe best to add functions

```r
addSpectra <- function(x, spectra)
updateSpectra <- function(x, spectra)
removeSpectra <- function(x, spectra)
```

Where `x` is a `CompDb` and `spectra` a `Spectra` object. Note that the `spectra` also need to have a reference to the compound in the compound table - which might have to be added before.

**Comment by michaelwitting** [comment]
A short question from my side: I have developed the MassBank backend, Steffen the Msp backend and maybe somebody else some other...
Shall at least the three/four/five of us agree on some common variable names, e.g. for InChIKey, SMILES, ID or so? Like this at least we don't have to map all the time between different preferences of variable naming. And maybe define a minimal set?
