### ISSUE TITLE
Prepare for Bioconductor submission

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/CompoundDb#90]
Prepare for submission to Bioconductor. Cleaning up code and un-needed (redundant) functionality.

- [x] Remove the `annotateMz` function.

**Comment by jorainer** [comment]
@stanstrup , @jmbadia , did any of you use the `annotateMz` function? I would like to remove that because we have a `matchMz` function in the `MetaboAnnotation` package that has more options and is *better*.

**Comment by jmbadia** [comment]
No, I was using compareSpectra to compare its features with the `annotate` function of MS2ID. I'll be more than happy to check your new matchMz :)

**Comment by jorainer** [comment]
CompoundDb was submitted to BioC - waiting for review.
